PortfolioBook/Areas/Admin/Models/UyeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PortfolioBook.Areas.Admin.Models
{
    public class UyeViewModel
    {
        public string UyeID { get; set; }
        public string KullaniciAdi { get; set; }
    }
}

PortfolioBook/Areas/Admin/Controllers/UyeController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PortfolioBook.Areas.Admin.Models;
using PortfolioBook.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortfolioBook.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UyeController : Controller
    {

        ApplicationDbContext db;
        public UyeController()
        {
            db = new ApplicationDbContext();
        }


        public ActionResult Index()
        {
            var uyeler = db.Users.Select(x => new UyeViewModel { UyeID = x.Id, KullaniciAdi = x.UserName }).ToList();

            return View(uyeler);
        }

        public ActionResult RolAta(string id)
        {
            var userManager = HttpContext.GetOwinContext().Get<ApplicationUserManager>();
            var user = userManager.FindById(id);

            if (user == null)
                return HttpNotFound();

            ViewBag.Roles = db.Roles.ToList();
            return View(user);
        }

        [HttpPost]
        public ActionResult RolAta(string userId, string[] roles)
        {
            var userManager = HttpContext.GetOwinContext().Get<ApplicationUserManager>();

            // yeni rollere kullanıcıyı bağlamadan önce, kullanıcının üzerindeki tüm rolleri kopartıyoruz:
            userManager.RemoveFromRoles(userId, userManager.GetRoles(userId).ToArray());

            if (roles != null)
            {
                foreach (var item in roles)
                {
                    userManager.AddToRole(userId, item);
                }
            }

            return RedirectToAction("Index");
        }
    }
}

PortfolioBook/Areas/Admin/Views/Uye/Index.cshtml
@model List<PortfolioBook.Areas.Admin.Models.UyeViewModel>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Kullanıcı Adı</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in Model)
            {
                <tr>
                    <td>@item.KullaniciAdi</td>
                    <td>@Html.ActionLink("Rol Değiştir", "RolAta", "Uye", new { id = item.UyeID }, new { @class = "btn btn-info" })</td>
                </tr>
            }
        }
    </tbody>
</table>

PortfolioBook/Areas/Admin/Views/Uye/RolAta.cshtml
@model PortfolioBook.Models.ApplicationUser
@using Microsoft.AspNet.Identity.EntityFramework
@{
    ViewBag.Title = "RolAta";
}

<h2>RolAta</h2>

<h2>Roller</h2>
<h3>Kullanıcı Adı: @Model.UserName</h3>

@using (Html.BeginForm())
{
    @Html.Hidden("userId", Model.Id)

    foreach (var item in ViewBag.Roles as IEnumerable<IdentityRole>)
    {
        <div class="checkbox">
            <label>
                <input type="checkbox" name="roles" value="@item.Name" checked="@Model.Roles.Any(x => x.RoleId.Equals(item.Id))" />
                @item.Name
            </label>
        </div>
    }

    <input type="submit" value="KAYDET" class="btn btn-success" />
}